server:
  port: ${port:0}

spring:
  application:
    name: facturacion-service
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: ${MYSQL_PASSWORD}
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
  jpa:
    hibernate:
    ddl-auto: update
    show-sql: false

  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672



message: hello from facturacion-service

management:
  endpoints:
    web:
      exposure:
        include: '*'
#